name: Docker Image CI for GHCR
on: 
  [push, workflow_dispatch]

env:
  IMAGE_NAME: ghcr.io/$GITHUB_REPOSITORY:${GITHUB_SHA:0:8}
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build and push the image
        run : |
          echo ${{ secrets.GH_PAT }} | docker login --username $GITHUB_REPOSITORY_OWNER --password-stdin ghcr.io
          rm -rf /home/runner/.docker/config.json
          echo $IMAGE_NAME
