name: Build and push to OCP
on: 
  [push, workflow_dispatch]
env:
  APP_NAME: isi-test-app
  LIMIT_CPU: 150m
  LIMIT_MEM: 512Mi
  REQUEST_CPU: 100m
  REQUEST_MEM: 512Mi
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build and push the image
        run : |
          echo ${{ secrets.GH_PAT }} | docker login --username $GITHUB_REPOSITORY_OWNER --password-stdin ghcr.io
          docker build -t ghcr.io/$GITHUB_REPOSITORY:${GITHUB_SHA:0:8} .
          docker push ghcr.io/$GITHUB_REPOSITORY:${GITHUB_SHA:0:8}
          rm -rf /home/runner/.docker/config.json
          
  publish_to_ocp:
    runs-on: [self-hosted]
    needs: build_and_push
    steps: 
      - name: Publish to OCP
        run : |
          cp /var/template/deployment/$GITHUB_REPOSITORY.yaml $RUNNER_TEMP/$GITHUB_SHA.yaml
          sed -i -e "s|{APP_NAME}|$APP_NAME|g" \
           -e "s|{IMAGE_NAME}|ghcr.io/$GITHUB_REPOSITORY:${GITHUB_SHA:0:8}|g" \
           -e "s|{LIMIT_CPU}|$LIMIT_CPU|g" \
           -e "s|{LIMIT_MEM}|$LIMIT_MEM|g" \
           -e "s|{REQUEST_CPU}|$REQUEST_CPU|g" \
           -e "s|{REQUEST_MEM}|$REQUEST_MEM|g" $RUNNER_TEMP/$GITHUB_SHA.yaml
          oc apply -f $RUNNER_TEMP/$GITHUB_SHA.yaml
          oc rollout status deployment/$APP_NAME
          oc get route $APP_NAME -o custom-columns=ROUTE:.spec.host --no-headers
          rm -rf $RUNNER_TEMP/$GITHUB_SHA.yaml
